name: Build and publish
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Build with dotnet
        run: dotnet build

      - name: dotnet publish
        run: dotnet publish -o "/var/www/portfolio"